CREATE TABLE IF NOT EXISTS egressos (
    `id` INT,
    `nomeCompactado` VARCHAR(21) CHARACTER SET utf8,
    `nome` VARCHAR(38) CHARACTER SET utf8,
    `email` VARCHAR(50) CHARACTER SET utf8,
    `linkedin` VARCHAR(72) CHARACTER SET utf8,
    `github` VARCHAR(33) CHARACTER SET utf8,
    `lattes` VARCHAR(38) CHARACTER SET utf8,
    `researchgate` VARCHAR(49) CHARACTER SET utf8,
    `facebook` VARCHAR(47) CHARACTER SET utf8,
    `twitter` VARCHAR(36) CHARACTER SET utf8,
    `instagram` VARCHAR(40) CHARACTER SET utf8,
    `stackoverflow` VARCHAR(53) CHARACTER SET utf8,
    `curso` VARCHAR(23) CHARACTER SET utf8,
    `campus` VARCHAR(7) CHARACTER SET utf8,
    `egresso` VARCHAR(4) CHARACTER SET utf8,
    `avatar` VARCHAR(16) CHARACTER SET utf8
);
INSERT INTO egressos VALUES
    (20062370361,'Aline Donato','Aline Donato Carreiro',NULL,'https://www.linkedin.com/in/alinedonato/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20052370067,'Alana Morais','Alana Marques de Morais','alana_mm@hotmail.com','https://www.linkedin.com/in/alana-morais-b6b0a195/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20052370342,'Alisson Sena','Alisson Alcoforado Sena de Lima','alisson.sena@gmail.com','https://www.linkedin.com/in/alisson-sena/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20051370225,'André Vinagre','André Nobre Vinagre','andrenvinagre@gmail.com','https://www.linkedin.com/in/andre-vinagre/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (041037087,'Andreza Vieira','Andreza de Sousa Vieira','andreza_sv@yahoo.com.br','https://www.linkedin.com/in/andrezavieira/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20061370422,'Anna Clara Nobrega','Anna Clara Rodrigues da Nobrega','acrnobrega@hotmail.com','https://www.linkedin.com/in/anna-clara-nobrega/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20061370040,'Andréa Bezerra','Andréa Fernanda Fontes Bezerra','dsi.andrea@hotmail.com','https://www.linkedin.com/in/andrea-fernanda-478a2660/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20112370505,'Alex Martins','Alex Martins Bezerra','alexmbezerrajp@gmail.com','https://www.linkedin.com/in/alex-martins-2b480023/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20071370107,'Ângelo Negreiros','Ângelo Lemos Vidal de Negreiros','angelolvnegreiros@hotmail',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20091370072,'Alessandra Silva','Alessandra Mendes da Silva',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20121370474,'Alexandre Dias','Alexandre Dias Sales De Morais','dias.jbr@gmail.com','https://www.linkedin.com/in/alexandre-dias-833a306a/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (042037154,'Alline Morais','Alline Silva de Morais','allinemorais@gmail.com','https://www.linkedin.com/in/alline-morais-psm-pspo-50002094/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20151370154,'Aluisio Fitipaldi','Aluisio Lins Fitipaldi','alfit@oi.com.br',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20102370022,'Amanda Silva','Amanda Alves Almeida da Silva',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20111370536,'Amanda Lopes','Amanda Lopes Fabricio','amandalops00@gmail.com','https://www.linkedin.com/in/mandalps/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (031037002,'Ana Cláudia Silva','Ana Cláudia Costa da Silva',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20102370030,'Ana Paula Vale','Ana Paula de Lucena Vale','apvalefin@gmail.com','https://www.linkedin.com/in/anapaulavale/','https://github.com/apvale',NULL,NULL,NULL,'http://twitter.com/apvale','https://www.instagram.com/aninhalvale/',NULL,'cstsi','ifpb-jp','True','20102370030.jpg'),
    (20132370403,'Anderson Araújo','Anderson de Araújo Gomes','anderson.araujo.g@gmail.com','https://www.linkedin.com/in/anderson-arg/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20131370094,'Anderson Leal','Anderson de Oliveira Ferreira Leal','andersonofl@gmail.com','https://www.linkedin.com/in/anderson-leal-295595a8/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20132370284,'André Alencar','André de Alencar Oliveira da Costa','andrealencar@outlook.com.br','https://www.linkedin.com/in/andreealencar/','https://github.com/andreealencar',NULL,NULL,NULL,'https://twitter.com/andreealencar',NULL,NULL,'cstsi','ifpb-jp','True','20132370284.jpg'),
    (20081370100,'André Caldas','André Fernandes de Caldas','andre.fcaldas@gmail.com','https://www.linkedin.com/in/andré-caldas-926ab220/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (042037148,'André Nunes','André Luiz Teixeira de Carvalho Nunes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (042037151,'Anselmo Gomes','Anselmo Lacerda Gomes',NULL,'https://www.linkedin.com/in/anselmo-lacerda-a6889531/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20052370016,'Antonio Lima','Antonio Josué de Lima Neto','josuedsi@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20082370030,'Antonio Mendonça','Antonio Ezequiel de Mendonça',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20122380163,'Antônio Muniz','Antônio Muniz de Andrade Neto','antoniomunizdeandrade@gmail.com','https://www.linkedin.com/in/antonio-muniz-79783a78',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstrc','ifpb-jp','True','20122380163.jpg'),
    (042037147,'Antonio Loureiro','Antonio Loureiro Cavalcanti Filho','antonniojp@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20131370078,'Antonio Palitot','Antonio de Pádua Palitot Júnior','jrpalitot@gmail.com','https://www.linkedin.com/in/antônio-palitot-2470b8149/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20121370172,'Arthur Carvalho','Arthur Emanuel Brandão Carvalho',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20082370308,'Arthur Luckwu','Arthur Varela Luckwu de Oliveira','arthurvluckwu@gmail.com','https://www.linkedin.com/in/arthur-luckwu/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20131370248,'Artur Araújo','Artur Benício Araújo','artur_benicio@hotmail.com','https://www.linkedin.com/in/arturaraujob/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (042037146,'Arthur Melo','Arthur Santos Araujo de Melo','arthur_santoss@yahoo.com.br',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20101370037,'Ayrton Nádgel','Ayrton Nádgel de Souza Silva','ayrton.nadgel@gmail.com','https://www.linkedin.com/in/ayrton-nadgel-6b420487/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20072370577,'Ayrton Herculano','Ayrton Douglas Rodrigues Herculano','ayrtondouglas@gmail.com','https://www.linkedin.com/in/ayrtondouglas/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (031037006,'Barbara Xavier','Barbara de Assis Xavier',NULL,'https://www.linkedin.com/in/barbara-xavier-psm-5a43362b/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (031037008,'Bettowen Oliveira','Bettowen Carvalho de Oliveira','bettowen@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20062370205,'Breno Queiroz','Breno Queiroz Vasconcelos de Souza','brenoqueiroz_@hotmail.com','https://www.linkedin.com/in/breno-queiroz-vasconcelos-de-souza-8646a827/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20092370238,'Bruno Braga','Bruno Braga Bezerril','bruno.ifpb@gmail.com','https://www.linkedin.com/in/bragabruno/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20092380187,'Bruno Molino','Bruno Esturba Molino','brunoesturba@yahoo.com.br','https://www.linkedin.com/in/bruno-esturba-molino-21845397/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstrc','ifpb-jp','True','20092380187.jpeg'),
    (20111370307,'Bruno Paulino','Bruno de Araújo Paulino','brunojppb@gmail.com','https://www.linkedin.com/in/brunojppb','https://github.com/brunojppb',NULL,NULL,'https://www.facebook.com/brunojppb','https://twitter.com/brunojppb','https://www.instagram.com/brunojppb1/','https://stackoverflow.com/users/2301092/bruno-paulino','cstsi','ifpb-jp','True','20111370307.jpg'),
    (20101370053,'Bruno Costa','Bruno Luis do Nascimento Costa','bruno.not@hotmail.com','https://www.linkedin.com/in/brunolncosta/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20062370264,'Carlos Carvalho','Carlos Augusto Ayres Carvalho','carlaojp@globo.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20051370365,'Carlos Diego Quirino','Carlos Diego Quirino Lima','diegoquirino@gmail.com','https://www.linkedin.com/in/carlos-diego-quirino-lima-27bbb039/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20052370334,'Cirino Refosco','Cirino Ferreira Refosco',NULL,'https://www.linkedin.com/in/cirino/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20121370270,'Claucio Sousa','Claucio De Oliveira Sousa',NULL,'https://www.linkedin.com/in/clauciosousa/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (032037079,'Claudiana Batista','Claudiana Pereira Batista','clauclau_batista@yahoo.com.br','https://www.linkedin.com/in/claudiana-batista-ba296030/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (031037012,'Claudio Piomonte','Claudio de Magalhães Piomonte',NULL,'https://www.linkedin.com/in/cpiomonte/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20091370374,'D''angellys Cavalcanti','D''angellys Cavalcanti Feitosa','dangellyscavalcanti@gmail.com','https://www.linkedin.com/in/dangellys-cavalcanti/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20072370801,'Daniel Cardoso','Daniel Fernandes Vilar Cardoso','fvcdaniel@gmail.com','https://www.linkedin.com/in/daniel-cardoso-51b52b29/','https://github.com/fvcdaniel','http://lattes.cnpq.br/4472098497391191',NULL,NULL,'https://twitter.com/fvcdaniel/',NULL,NULL,'cstsi','ifpb-jp','True','20072370801.jpg'),
    (20102370081,'Daniel Filho','Daniel Alves de Lima Filho','afilhodaniel@gmail.com','https://www.linkedin.com/in/afilhodaniel/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (032037038,'Danilo Dutra','Danilo Lima Dutra','nilosurfer@hotmail.com','https://www.linkedin.com/in/danilolimadutra/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (042037140,'Danilo Lucena','Danilo Carlos Gouveia de Lucena','ryganon_stu@yahoo.com.br','https://www.linkedin.com/in/danilo-lucena-a09459a7/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20082370391,'Danúbia Lima','Danúbia Lima da Silva Almeida','biaeccentric@gmso.com','https://www.linkedin.com/in/danúbia-lima-14b5732b/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20091370030,'Daniel Vilar','Daniel Vilar Pereira',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20111370439,'Daniela Pitta','Daniela Pitta de Jesus','daniela.pdj@gmail.com','https://www.linkedin.com/in/dlpitta/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20091370188,'Davi Bandeira','Davi Cavalcanti Pinto Bandeira','davibandeira@gmail.com','https://www.linkedin.com/in/davi-bandeira-2651b325/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20112370394,'David Veloso','David Edson Ramos Veloso','davidedsoon@gmail.com ','https://www.linkedin.com/in/davidveloso/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20051370160,'David Viana','David Henrique de Moura Viana',NULL,'https://www.linkedin.com/in/david-moura-a6863016a/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20061370082,'Dawson Brito','Dawson Jansen Gomes Enedino Brito',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20061370139,'David Amaral','David Saraiva do Amaral Filho',NULL,'https://www.linkedin.com/in/amaraldavi1/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (032037073,'Deijiane Carvalho','Deijiane Gomes Matsumoto de Carvalho',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20102370090,'Denilson Dantas','Denilson Henrique Dantas','denilsontakezo@hotmail.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20091370331,'Didier Ferreira','Didier Braz Ferreira','didierpg@hotmail.com','https://www.linkedin.com/in/didier-ferreira-3a1168161/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20061370155,'Diêgo Bulhões','Diêgo Michel Ferreira Bulhões',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (032037069,'Diego Lins','Diego Jonio Borba Lins',NULL,'https://www.linkedin.com/in/diegojonio/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20081370371,'Diêgo Medeiros','Diêgo Felipe de Medeiros','diego_toxicity@hotmail.co','https://www.linkedin.com/in/dfmedeiros/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20061370112,'Diego Pessoa','Diego Ernesto Rosa Pessoa','diegopessoa12@gmail.com','http://linkedin.com/in/diego-pessoa-6a137b28/','https://github.com/diegoep','http://lattes.cnpq.br/4442363726982518','https://www.researchgate.net/profile/Diego_Pessoa',NULL,'https://twitter.com/diegopessoa/',NULL,NULL,'cstsi','ifpb-jp','True','20061370112.jpg'),
    (20082370154,'Diego Nóbrega','Diego Madson de Andrade Nóbrega','diegomadson@msn.com','https://www.linkedin.com/in/diego-madson-nobrega-b8854b2b/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20051370322,'Diénert Vieira','Diénert de Alencar Vieira','dienertalencar@gmail.com','https://www.linkedin.com/in/di%C3%A9nert-vieira-6961b616/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True','20051370322.jpg'),
    (20081370312,'Diógenes Fernandes','Diógenes Augusto Fernandes Hermínio','diofeher@gmail.com','https://www.linkedin.com/in/diofeher/','https://www.github.com/diofeher/',NULL,NULL,'https://www.facebook.com/diofeher/','https://www.twitter.com/diofeher/','https://www.instagram.com/diofeher/',NULL,'cstsi','ifpb-jp','True','20081370312.jpg'),
    (20072370437,'Diógenes Calado','Diógenes Calado da Silva','diogenes_c1@hotmail.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20082370235,'Diogo Alves','Diogo de Alcantara Rodrigues Alves','diogoca@gmail.com','https://www.linkedin.com/in/diogoca/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20072370461,'Douglas Silva','Douglas Limeira Silva',NULL,'https://www.linkedin.com/in/douglas-limeira-silva-04723429/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20112370319,'Douglas Torres','Douglas Gadelha Firmino Torres','douglastorr@gmail.com','https://www.linkedin.com/in/dougtorres/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20112370238,'Éder Pires','Éder Pires Batista',NULL,'https://www.linkedin.com/in/eder-pires-a46b867b/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (032037084,'Edno França','Edno Galderisy Ferreira de França',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20101380121,'Eduardo Fox','Eduardo Farias Brinds-Ley Fox','eduardobfox@gmail.com',NULL,NULL,'http://lattes.cnpq.br/1754631372530799',NULL,NULL,NULL,NULL,NULL,'cstrc','ifpb-jp','True','20101380121.png'),
    (042037138,'Elias Júnior','Elias Pereira Gomes Júnior',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (041037103,'Emerson Diego','Emerson Diego da Costa Araújo','diegowebby@gmail.com.br','https://www.linkedin.com/in/emerson-diego/','https://github.com/emerson-diego','http://lattes.cnpq.br/8718633182693616',NULL,'https://www.facebook.com/emerson.diego.14','https://twitter.com/diegowebby',NULL,NULL,'cstsi','ifpb-jp','True','041037103.jpg'),
    (20091370080,'Érico Ramos','Érico Vinicius da Silva Ramos','evsramos@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20151380265,'Erick Câmara','Erick Câmara dos Santos','erickcamara3@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstrc','ifpb-jp','True',NULL),
    (042037165,'Elaine Araújo','Elaine Cristina Juvino de Araújo',NULL,'https://www.linkedin.com/in/elaine-araujo-31730618/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20092370297,'Elias Rocha','Elias Medeiros da Rocha','eliasipj@yahoo.com.br','https://www.linkedin.com/in/eliasmrocha/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20131370043,'Elias Rocha','Elias Felipe da Rocha',NULL,'https://www.linkedin.com/in/elias-rocha-4b2a6733/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20102370111,'Emerson Raniere','Emerson Raniere Oliveira Souza','emersonraniere@hotmail.com','https://www.linkedin.com/in/emersonraniere/','https://github.com/EmersonRaniere',NULL,NULL,'https://www.facebook.com/EmersonRaniere','https://twitter.com/_EmersonRaniere','https://www.instagram.com/EmersonRaniere',NULL,'cstsi','ifpb-jp','True','20102370111.jpg'),
    (20061370180,'Erisvaldo Gadelha','Erisvaldo Gadelha Saraiva Junior','jun1nho_jp@hotmail.com','https://www.linkedin.com/in/erisvaldojunior/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20102370120,'Érycson Nóbrega','Érycson Gomes da Nóbrega','egdn2004@gmail.com','https://www.linkedin.com/in/érycson-nóbrega-ba5734103/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20121370415,'Evandro Macedo','Evandro Henrique Cordeiro de Macedo','evandro.hcm@gmail.com','https://www.linkedin.com/in/evandrohcm','https://github.com/evandromacedo',NULL,NULL,'https://facebook.com/macedoevandro','https://twitter.com/evandromacedo_','https://www.instagram.com/evan.macedo',NULL,'cstsi','ifpb-jp','True','20121370415.jpg'),
    (20072370682,'Ewerton Lima','Ewerton Henrique Silva de Lima','https://www.linkedin.com/in/ewerton-lima-97bb4720/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20071370239,'Fábio Albuquerque','Fábio Cruz Barbosa de Albuquerque','fabiumcruz@gmail.com','https://www.linkedin.com/in/fabiocbalbuquerque/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20071370042,'Felipe Batista','Felipe Dantas de Assis e M. Batista','felipedantas89@msn.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20131370124,'Fellipe Freire','Fellipe Freire Cirilo Passos','fellipe91 @gmail.com','https://www.linkedin.com/in/fellipe-freire-31295050/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20071370077,'Flavio Lima','Flavio Eduardo Correia Lima de Menezes','flavio.correialima@yahoo.com.br','https://www.linkedin.com/in/flavio-correialima/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20071610175,'Flavio Ribeiro','Flavio Ribeiro Nogueira Barbosa','email@flavioribeiro.com','https://www.linkedin.com/in/flavioribeiro/','https://github.com/flavioribeiro',NULL,NULL,NULL,'https://twitter.com/flavioribeiro','https://twitter.com/flavioribeironb',NULL,'Engenharia Eletrica','ifpb-jp','True',NULL),
    (011025083,'Flaviano Flauber','Flaviano Flauber de Lira Marinho','flauberjp@gmail.com','https://www.linkedin.com/in/flauber/','https://github.com/flauberjp',NULL,NULL,NULL,'https://www.instagram.com/flauberjp/',NULL,NULL,'CST EM TELECOMUNICAÇÕES','ifpb-jp','True','09571013.jpg'),
    (042037135,'Francisco Alencar','Francisco Dellano Leite Alencar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (041037090,'Francisco Dantas','Francisco Dantas Nobre Neto',NULL,'https://www.linkedin.com/in/francisco-dantas-nobre-neto-76a003138/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL),
    (20132380212,'Gabriel da Silva','Gabriel da Silva Cavalcante','gabrielsc.adm@gmail.com','https://www.linkedin.com/in/gcavalcante/',NULL,NULL,NULL,'https://www.facebook.com/gabriel.cavalcante.adm',NULL,NULL,NULL,'cstrc','ifpb-jp','True','20132380212.jpg'),
    (20051370012,'Gabriela Souza','Gabriela Guedes Souza',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'cstsi','ifpb-jp','True',NULL);
